// ============================================================
// DEMIURGOS — Vector Store (In-Memory + Persistent)
// ============================================================
//
// In-memory vector store with SQLite persistence.
// Supports real sentence-transformer embeddings via EmbeddingClient
// with automatic fallback to hash-based embeddings.

import Database from 'better-sqlite3';
import { randomUUID } from 'node:crypto';
import { simpleEmbed, cosineSimilarity, EmbeddingClient } from './embeddings.js';

export interface VectorEntry {
  id: string;
  text: string;
  embedding: number[];
  metadata: Record<string, string | number | boolean>;
  createdAt: Date;
  /** True if embedding was generated by the real embedding server */
  isRealEmbedding?: boolean;
}

export interface SearchResult {
  entry: VectorEntry;
  similarity: number;
}

/**
 * Serialize a float array to a binary Buffer for BLOB storage.
 */
function serializeVector(vec: number[]): Buffer {
  const buf = Buffer.alloc(vec.length * 8); // Float64 = 8 bytes
  for (let i = 0; i < vec.length; i++) {
    buf.writeDoubleBE(vec[i], i * 8);
  }
  return buf;
}

/**
 * Deserialize a binary Buffer back to a float array.
 */
function deserializeVector(buf: Buffer): number[] {
  const count = buf.length / 8;
  const vec: number[] = new Array(count);
  for (let i = 0; i < count; i++) {
    vec[i] = buf.readDoubleBE(i * 8);
  }
  return vec;
}

export class VectorStore {
  private entries: Map<string, VectorEntry> = new Map();
  private db: Database.Database;
  private collection: string;
  private embeddingClient: EmbeddingClient;
  private useRealEmbeddings: boolean = false;
  private initialized: boolean = false;

  constructor(dbPath = 'demiurgos-vectors.db', collection = 'default') {
    this.db = new Database(dbPath);
    this.db.pragma('journal_mode = WAL');
    this.collection = collection;
    this.embeddingClient = EmbeddingClient.getInstance();

    this.db.exec(`
      CREATE TABLE IF NOT EXISTS vectors (
        id TEXT PRIMARY KEY,
        collection TEXT NOT NULL,
        text TEXT NOT NULL,
        embedding TEXT NOT NULL,
        metadata TEXT NOT NULL DEFAULT '{}',
        created_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
      CREATE INDEX IF NOT EXISTS idx_vectors_collection ON vectors(collection);
    `);

    // Add vector_data BLOB column if it doesn't exist (migration)
    this.migrateAddVectorData();

    // Load existing entries into memory
    this.loadFromDisk();
  }

  /**
   * Initialize the embedding client and determine embedding mode.
   * Call this before add/search for best results with real embeddings.
   */
  async initialize(): Promise<void> {
    if (this.initialized) return;
    this.useRealEmbeddings = await this.embeddingClient.isAvailable();
    if (this.useRealEmbeddings) {
      console.log('[Demiurgos] VectorStore using real sentence-transformer embeddings');
    } else {
      console.log('[Demiurgos] VectorStore using hash-based fallback embeddings');
    }
    this.initialized = true;
  }

  /**
   * Add text to the vector store. Automatically generates embedding.
   * Uses real embeddings if the embedding server is available.
   */
  add(text: string, metadata: Record<string, string | number | boolean> = {}): string {
    const id = randomUUID();
    const embedding = simpleEmbed(text);
    const entry: VectorEntry = {
      id,
      text,
      embedding,
      metadata,
      createdAt: new Date(),
      isRealEmbedding: false,
    };

    this.entries.set(id, entry);

    // Persist to disk
    this.db.prepare(`
      INSERT INTO vectors (id, collection, text, embedding, metadata)
      VALUES (?, ?, ?, ?, ?)
    `).run(id, this.collection, text, JSON.stringify(embedding), JSON.stringify(metadata));

    return id;
  }

  /**
   * Add text with real embedding from the embedding server.
   * Falls back to hash-based if server is unavailable.
   */
  async addAsync(text: string, metadata: Record<string, string | number | boolean> = {}): Promise<string> {
    if (!this.initialized) {
      await this.initialize();
    }

    const id = randomUUID();
    let embedding: number[];
    let isReal = false;

    if (this.useRealEmbeddings) {
      embedding = await this.embeddingClient.embed(text);
      isReal = this.embeddingClient.isUsingRealEmbeddings();
    } else {
      embedding = simpleEmbed(text);
    }

    const entry: VectorEntry = {
      id,
      text,
      embedding,
      metadata,
      createdAt: new Date(),
      isRealEmbedding: isReal,
    };

    this.entries.set(id, entry);

    // Persist to disk with both JSON and binary vector
    const vectorBlob = isReal ? serializeVector(embedding) : null;
    this.db.prepare(`
      INSERT INTO vectors (id, collection, text, embedding, metadata, vector_data)
      VALUES (?, ?, ?, ?, ?, ?)
    `).run(id, this.collection, text, JSON.stringify(embedding), JSON.stringify(metadata), vectorBlob);

    return id;
  }

  /**
   * Search for similar text. Returns top-k results sorted by similarity.
   */
  search(query: string, topK = 5, minSimilarity = 0): SearchResult[] {
    const queryEmbedding = simpleEmbed(query);

    const results: SearchResult[] = [];

    for (const entry of this.entries.values()) {
      // Only compare with compatible embeddings (same dimension)
      if (entry.embedding.length !== queryEmbedding.length) continue;
      const similarity = cosineSimilarity(queryEmbedding, entry.embedding);
      if (similarity >= minSimilarity) {
        results.push({ entry, similarity });
      }
    }

    return results
      .sort((a, b) => b.similarity - a.similarity)
      .slice(0, topK);
  }

  /**
   * Search using real embeddings from the server.
   * Falls back to hash-based search when server is unavailable.
   */
  async searchAsync(query: string, topK = 5, minSimilarity = 0): Promise<SearchResult[]> {
    if (!this.initialized) {
      await this.initialize();
    }

    if (!this.useRealEmbeddings) {
      return this.search(query, topK, minSimilarity);
    }

    const queryEmbedding = await this.embeddingClient.embed(query);

    // If the client fell back to hash-based, use synchronous search
    if (!this.embeddingClient.isUsingRealEmbeddings()) {
      this.useRealEmbeddings = false;
      return this.search(query, topK, minSimilarity);
    }

    const results: SearchResult[] = [];

    for (const entry of this.entries.values()) {
      // Match real embeddings with real, hash with hash
      if (entry.embedding.length !== queryEmbedding.length) continue;
      const similarity = cosineSimilarity(queryEmbedding, entry.embedding);
      if (similarity >= minSimilarity) {
        results.push({ entry, similarity });
      }
    }

    return results
      .sort((a, b) => b.similarity - a.similarity)
      .slice(0, topK);
  }

  /**
   * Delete an entry by ID.
   */
  delete(id: string): boolean {
    const existed = this.entries.delete(id);
    if (existed) {
      this.db.prepare('DELETE FROM vectors WHERE id = ? AND collection = ?')
        .run(id, this.collection);
    }
    return existed;
  }

  /**
   * Delete entries older than maxAge (milliseconds).
   */
  purgeExpired(maxAgeMs: number): number {
    const cutoff = new Date(Date.now() - maxAgeMs);
    let purged = 0;

    for (const [id, entry] of this.entries) {
      if (entry.createdAt < cutoff) {
        this.entries.delete(id);
        purged++;
      }
    }

    if (purged > 0) {
      this.db.prepare(`
        DELETE FROM vectors WHERE collection = ? AND created_at < datetime('now', ?)
      `).run(this.collection, `-${Math.floor(maxAgeMs / 1000)} seconds`);
    }

    return purged;
  }

  /**
   * Get total number of entries.
   */
  size(): number {
    return this.entries.size;
  }

  /**
   * Clear all entries in this collection.
   */
  clear(): void {
    this.entries.clear();
    this.db.prepare('DELETE FROM vectors WHERE collection = ?').run(this.collection);
  }

  /**
   * Check if the store is using real embeddings.
   */
  isUsingRealEmbeddings(): boolean {
    return this.useRealEmbeddings;
  }

  // --- Internal ---

  private migrateAddVectorData(): void {
    // Check if vector_data column exists
    const columns = this.db.prepare("PRAGMA table_info(vectors)").all() as { name: string }[];
    const hasVectorData = columns.some((col) => col.name === 'vector_data');

    if (!hasVectorData) {
      this.db.exec('ALTER TABLE vectors ADD COLUMN vector_data BLOB');
    }
  }

  private loadFromDisk(): void {
    const rows = this.db.prepare(
      'SELECT id, text, embedding, metadata, created_at, vector_data FROM vectors WHERE collection = ?'
    ).all(this.collection) as {
      id: string;
      text: string;
      embedding: string;
      metadata: string;
      created_at: string;
      vector_data: Buffer | null;
    }[];

    for (const row of rows) {
      const hasRealVector = row.vector_data != null && row.vector_data.length > 0;
      this.entries.set(row.id, {
        id: row.id,
        text: row.text,
        embedding: hasRealVector
          ? deserializeVector(row.vector_data!)
          : JSON.parse(row.embedding),
        metadata: JSON.parse(row.metadata),
        createdAt: new Date(row.created_at),
        isRealEmbedding: hasRealVector,
      });
    }
  }
}
